### ISSUE TITLE
MuirGlacier support

### ISSUE THREAD

**Issue by kushal256** [Ambisafe/etoken-lib#4]
Hi is there any recommendation on how to get my etoken-lib to point to an ethereumjs-vm with MuirGlacier support?

**Comment by lastperson** [comment]
@kushal256 can you show an example of how you initialize it? In general you don't need to do anything special if you can run your vm as an app, listening on some port.

**Comment by kushal256** [comment]
Thanks for your assistance @lastperson I was looking down the wrong path

**Comment by Armen-Arakelian** [comment]
чувоки, чего мне вдруг пришло это уведомление?)
